---
title: "04_analysis"
author: "Evan Muise"
date: "5/20/2021"
output: html_document
---

Setup!

```{r setup}
library(tidyverse) # in use
library(tidymodels) # t tests
library(cowplot) # plot additions
library(ggrepel) # for t-test plot
library(ggridges) # for ridge plot
#library(ggpubr)

library(sf) # in use
library(raster) # in use for data

library(ggsci) # in use for aaas
library(scico) # in use for ridge plot
#library(ggthemes) 
theme_set(theme_bw())
set.seed(69420)

source(here::here("scripts", "get_keys.R"))
```

Merged DF methods

```{r process, message=FALSE}
full_dfs <- list.files(here::here("data", "all_vars"), 
                       pattern = ".csv", full.names = T)

process_csv <- function(df) {
  print(df)
  
  split <- str_split(df, pattern = "/")
  if (is.character(df)) {
    df <- read_csv(df, col_types = cols())
  }

  df <- df %>%
    filter(vlce != 0) %>% # filter out unclassified pixels
    filter(elev < 32000) # filter out elevation nodata pixels (very small amount)
  
  cont <- df %>% 
    filter(vlce %in% c(230, 220, 210, 81)) %>% # forested pixels
    filter(Change_Attribution != 2) %>% # filter out harvested pixels
    select(subzone, protected, elev:total_biomass, vlce)
  
  # for slice_sample in next pipes
  cont_cells <- cont %>% count(protected) %>% pull(n) %>% min()
  
  both <- cont %>% count(protected) %>% pull(n) %>% length()
  # check if both protected and unprotected exists
  
  if (cont_cells != 0 & both == 2) {
  
    cont <- cont %>%
      group_by(protected) %>%
      slice_sample(n = cont_cells) # get same no. pixels prot and unprot
    
    sample_loc <- here::here("data", "all_vars", "sampled")
    
    
    sample_name <- tail(split[[1]], 1)
    
    print("saving sampled df")
    write_csv(cont, here::here(sample_loc, sample_name))
    
    cont_t_tests <- cont %>%
      pivot_longer(cols = elev:total_biomass, names_to = "variable") %>%
      group_by(subzone, variable, protected) %>%
      nest() %>%
      pivot_wider(names_from = protected, values_from = data) %>%
      ungroup() %>%
      mutate(
        t_test = map2(protected, unprotected, ~{t.test(.x$value, .y$value) %>% 
                 tidy()})
      ) %>%
      select(!c("protected", "unprotected")) %>%
      unnest(cols = t_test)
    
  } else {
    
    cont_t_tests <- tibble()
    
  }
    
  if (nrow(df) > 0) {
    
    # change wants harvest included, so operates on df, rather than disc
    change <- df %>%
      count(subzone, protected, Change_Attribution) %>%
      group_by(subzone, protected) %>%
      mutate(per_dist = n / sum(n))
    
    elev_dist <- df %>%
      group_by(subzone, protected, elev, Change_Attribution) %>%
      summarize(count = n())
    
    # remove harvested pixels post here
    
    disc <- df %>%
      filter(Change_Attribution != 2) %>% # remove harvested pixels
      select(subzone, protected, vlce, Change_Attribution, change_year)
    
    
    vlce <- disc %>%
      count(subzone, protected, vlce) %>%
      group_by(subzone, protected) %>%
      mutate(per_cover = n / sum(n))
    
    elev_nw <- df %>% 
      filter(Change_Attribution != 2) %>% # remove harvested pixels
      left_join(keys$vlce, by = c("vlce" = "class_val")) %>%
      filter(class_name != "water") %>%
      group_by(subzone, protected, elev, class_name) %>%
      summarize(count = n())
    
    elev_w <- df %>% 
      filter(Change_Attribution != 2) %>% # remove harvested pixels
      left_join(keys$vlce, by = c("vlce" = "class_val")) %>%
      group_by(subzone, protected, elev, class_name) %>%
      summarize(count = n())
    
    lat_dist <- df %>%
      group_by(subzone, protected, latitude, Change_Attribution) %>%
      summarize(count = n())
    
    
  } else {
    
    disc <- tibble()
    vlce <- tibble()
    change <- tibble()
    elev_nw <- tibble()
    elev_w <- tibble()
    elev_dist <- tibble()
    lat_dist <- tibble()
    
  }
  
  outputs <- list("cont_t_tests" = cont_t_tests, 
                  "vlce" = vlce, 
                  "change" = change,
                  "elev_nw" = elev_nw,
                  "elev_w" = elev_w,
                  "elev_dist" = elev_dist,
                  "lat_dist" = lat_dist)
    
    #names(outputs) <- c("cont_t_tests", "vlce", "change")
    
  return(outputs)
  
}

outs <- map(full_dfs, process_csv)

t_tests <- bind_rows(map(outs, 1))

vlce <- bind_rows(map(outs, 2)) %>%
  ungroup() %>%
  complete(subzone, protected, vlce, 
           fill = list(n = 0, per_cover = 0))

change <- bind_rows(map(outs, 3)) %>%
  ungroup() %>%
  complete(subzone, protected, Change_Attribution, 
           fill = list(n = 0, per_dist = 0))

elev_nw <- bind_rows(map(outs, 4))

elev_w <- bind_rows(map(outs, 5))

elev_dist <- bind_rows(map(outs, 6))

lat_dist <- bind_rows(map(outs, 7))

#structure <- bind_rows(map(outs, 7))
structure <- read_csv(here::here("data", "structure", "structure_means.csv"))
```

```{r save}
save.image(file = here::here("data", "backup.RData"))
```

```{r load}
load(here::here("data", "backup.RData"))
```

```{r setup-2}
elev_agg <- 50
vlce_colours <- keys$vlce %>% pull(ntems_colour) %>% rev()
```

Elevation & Protected/Unprotected (BEC) Figures

```{r elev-bec}
elev_zone_data <- elev_nw %>% 
  ungroup() %>%
  filter(elev < 32000) %>%
  separate(subzone, into = c("zone", "subzone")) %>% 
  group_by(protected, elev, zone) %>% 
  summarize(n = sum(count)) %>% 
  mutate(perc = n / sum(n)) 

elev_20m <- elev_zone_data %>%
  mutate(elev = elev %/% elev_agg * elev_agg) %>%
  group_by(protected, elev, zone) %>%
  summarize(n = sum(n)) %>%
  mutate(perc = n / sum(n))

elev_zone_plot_20m <- elev_20m %>%
  ggplot(aes(x = elev, y = perc, fill = zone)) +
  geom_area(stat = "identity") +
  facet_wrap(~str_to_title(protected)) +
  coord_flip() +
  scale_y_continuous(labels = scales::percent) +
  labs(x = "Elevation (m)",
       y = "Percent Cover",
       fill = "BEC Zone") +
  theme(legend.position = "left") +
  scale_fill_igv()

protected_elev <- elev_zone_data %>%
  ungroup() %>%
  pivot_wider(values_from = n, names_from = protected) %>% 
  group_by(elev) %>%
  summarize(protected = sum(protected, na.rm = T),
            unprotected = sum(unprotected, na.rm = T)) %>%
  mutate(total = protected + unprotected,
         per_prot = protected / total,
         per_unprot = 1 - per_prot) %>%
  pivot_longer(per_prot:per_unprot, names_to = "value", values_to = "percent")

# NOTE THE GEOM SMOOTH RATHER THAN LINE, DUE TO HIGH AND LOW ELEV LOW NUMBER
# OF PIXELS
prot_elev_plot <- protected_elev %>%
  ggplot(aes(x = elev, y = per_prot)) +
  #geom_smooth() +
  #geom_point() +
  geom_line() +
  scale_y_continuous(labels = scales::percent, limits = c(0, 1)) +
  labs(x = "Elevation (m)",
       y = "Percent Protected") +
  coord_flip()

prot_elev_plot_20m <- protected_elev %>% 
  mutate(elev = elev %/% elev_agg * elev_agg) %>% 
  group_by(elev) %>%
  summarize(protected = sum(protected),
            unprotected = sum(unprotected)) %>%
  mutate(total = protected + unprotected,
         per_prot = protected / total,
         per_unprot = 1 - per_prot) %>%
  ggplot(aes(x = elev, y = per_prot)) +
  #geom_smooth() +
  #geom_point() +
  geom_area() +
  scale_y_continuous(labels = scales::percent, limits = c(0, 1)) +
  labs(x = NULL,
       y = "Percent Protected",
       fill = NULL) +
  theme(axis.text.y = element_blank(),
        legend.position = c(0.7, 0.85)) +
  coord_flip()

mosaic_elev_plot <- plot_grid(elev_zone_plot_20m, prot_elev_plot_20m,
          rel_widths = c(3, 1),
          align = 'h', axis = 'tb')

ggsave(here::here("outputs", "bec_elev.png"), plot = mosaic_elev_plot, device = "png")

bec_legend <- cowplot::get_legend(elev_zone_plot_20m)

protected_elev %>% 
  mutate(elev = elev %/% elev_agg * elev_agg) %>% 
  group_by(elev) %>%
  summarize(protected = sum(protected),
            unprotected = sum(unprotected)) %>%
  mutate(total = protected + unprotected,
         per_prot = protected / total,
         per_unprot = 1 - per_prot,
         per_bc = total / sum(total)) %>%
  dplyr::select(elev, per_prot, per_bc) %>%
  pivot_longer(starts_with("per")) %>%
  ggplot(aes(x = elev, y = value, colour = name)) +
  #geom_smooth() +
  #geom_point() +
  geom_line() +
  scale_y_continuous(labels = scales::percent, limits = c(0, 1)) +
  scale_colour_manual(values = c("red",
                                 "blue"),
                      labels = c("Percent of BC",
                                 "Percent Protected")) +
  labs(x = "Elevation (m)",
       y = NULL,
       fill = NULL,
       colour = NULL,
       size = "Proportion of British Columbia") #+
  #theme(axis.text.y = element_blank()) +
  #coord_flip()
```

Elevation & Protected/Unprotected (VLCE) Figures

```{r elev-vlce}
elev_lcc_nw <- elev_w %>%
  filter(elev < 32000) %>%
  mutate(elev = elev %/% elev_agg * elev_agg) %>%
  group_by(protected, elev, class_name) %>%
  summarize(n = sum(count)) %>%
  mutate(perc = n / sum(n)) %>%
  left_join(keys$vlce) %>%
  mutate(name_clean = fct_rev(fct_reorder(name_clean, class_val)))

elev_lcc_20m <- elev_lcc_nw %>%
  ggplot(aes(x = elev, y = perc, fill = name_clean)) +
  geom_area(stat = "identity") +
  coord_flip() +
  facet_wrap(~str_to_title(protected)) +
  #coord_flip() +
  scale_y_continuous(labels = scales::percent) +
  scale_fill_manual(values = vlce_colours) +
  labs(x = "Elevation (m)",
       y = "Percent Cover",
       fill = "Land Cover") +
  theme(legend.position = "left")

mosaic_lcc_plot <- plot_grid(elev_lcc_20m, prot_elev_plot_20m,
          rel_widths = c(3, 1),
          align = 'h', axis = 'tb')

ggsave(here::here("outputs", "lcc_elev.png"), plot = mosaic_lcc_plot, device = "png")
```

Elevation and Disturbance

```{r elev-dist}
elev_dist_plot <- elev_dist %>% 
  mutate(elev = elev %/% elev_agg * elev_agg,
         Change_Attribution = ifelse(!(Change_Attribution %in% c(1, 2)), 
                                     NA, 
                                     Change_Attribution)) %>%
  group_by(protected, elev, Change_Attribution) %>%
  summarize(count = sum(count)) %>%
  mutate(perc = count / sum(count),
         Change_Attribution = case_when(Change_Attribution == 1 ~ "Fire",
                                        Change_Attribution == 2 ~ "Harvest",
                                        TRUE ~ "None")) %>%
  ggplot(aes(x = elev, y = perc, fill = Change_Attribution)) +
  geom_area(stat = "identity") +
  coord_flip() +
  facet_wrap(~str_to_title(protected)) +
  #coord_flip() +
  scale_y_continuous(labels = scales::percent) +
  #scale_fill_manual(values = vlce_colours) +
  labs(x = "Elevation (m)",
       y = "Percent Disturbed",
       fill = "Disturbance") +
  theme(legend.position = "left")

plot_grid(elev_dist_plot, prot_elev_plot_20m,
          rel_widths = c(3, 1),
          align = 'h', axis = 'tb')
```


Donut Plots

```{r donut}
# disturbance
change_donut <- change %>%
  mutate(Change_Attribution = ifelse(!(Change_Attribution %in% c(1, 2)), 
                                     NA, 
                                     Change_Attribution)) %>%
  group_by(protected, Change_Attribution) %>%
  summarize(count = sum(n, na.rm = T)) %>%
  mutate(perc = count / sum(count),
         Change_Attribution = case_when(Change_Attribution == 1 ~ "Fire",
                                        Change_Attribution == 2 ~ "Harvest",
                                        TRUE ~ "None")) 

change_donut %>%
  ggplot(aes(x = protected, y = perc, fill = Change_Attribution)) +
  geom_bar(stat = "identity") +
  guides(fill = guide_legend(reverse = F)) +
  theme_void() +
  theme(legend.position = "bottom") +
  coord_polar(theta = "y") +
  labs(fill = "Disturbance") +
  guides(fill = guide_legend(title.position = "top",
                             title.hjust = 0.5))

# BEC
bec_donut <- vlce %>%
  separate(subzone, into = c("zone", "subzone")) %>%
  group_by(protected, zone) %>%
  summarize(count = sum(n, na.rm = T)) %>%
  mutate(perc = count / sum(count)) 

bec_double_donut <- bec_donut %>%
  ggplot(aes(x = protected, y = perc, fill = zone)) +
  geom_bar(stat = "identity", position = "stack") +
  guides(fill = guide_legend(reverse = F)) +
  theme_void() +
  theme(legend.position = "bottom") +
  coord_polar(theta = "y") +
  labs(fill = "BEC Zone") +
  scale_fill_igv() +
  guides(fill = guide_legend(title.position = "top",
                             title.hjust = 0.5))

ggsave(here::here("outputs", "bec_double_donut.png"), 
       plot = bec_double_donut, device = "png")

bec_donut %>%
  ggplot(aes(x = zone, y = perc, fill = zone)) +
  geom_bar(stat = "identity") +
  geom_hline(yintercept = seq(0, .2, .1), lty = "dashed") +
  coord_polar() +
  scale_fill_igv() +
  facet_wrap(~str_to_title(protected)) +
  #theme_void() +
  theme(legend.position = "bottom") +
  labs(fill = NULL,
       x = NULL)

# VLCE  
vlce_donut <- vlce %>%
  group_by(protected, vlce) %>%
  summarize(count = sum(n, na.rm = T)) %>%
  left_join(keys$vlce, by = c("vlce" = "class_val")) %>%
  mutate(perc = count / sum(count, na.rm = T),
         name_clean = fct_reorder(name_clean, vlce)) 

vlce_double_donut <- vlce_donut %>%
  ggplot(aes(x = protected, y = perc, fill = name_clean)) +
  geom_bar(stat = "identity", position = "stack") +
  guides(fill = guide_legend(reverse = F)) +
  theme_void() +
  theme(legend.position = "bottom") +
  coord_polar(theta = "y") +
  labs(fill = "Land Cover") +
  scale_fill_manual(values = rev(vlce_colours)) +
  guides(fill = guide_legend(title.position = "top",
                             title.hjust = 0.5))

ggsave(here::here("outputs", "vlce_double_donut.png"), 
       plot = vlce_double_donut, device = "png")


vlce_donut %>%
  ggplot(aes(x = name_clean, y = perc, fill = name_clean)) +
  geom_bar(stat = "identity") +
  #geom_hline(yintercept = c(0, .25, .5, .75, 1), lty = "dashed") +
  coord_polar(theta = "x") +
  scale_fill_manual(values = rev(vlce_colours)) +
  facet_wrap(~str_to_title(protected)) +
  theme_void() +
  theme(legend.position = "bottom") +
  labs(fill = NULL)

```

Figure 1: BEC proportions

```{r bec-prop}
bec <- vlce %>%
  separate(subzone, into = c("zone", "subzone")) %>%
  group_by(protected, zone) %>%
  summarize(count = sum(n, na.rm = T)) %>%
  mutate(perc = count / sum(count))

bec %>%
  ggplot(aes(x = zone, y = perc, fill = str_to_title(protected))) +
  geom_col(position = "dodge") +
  labs(x = "Zone",
       y = "Percent",
       fill = NULL) +
  #coord_flip() +
  scale_y_continuous(labels = scales::percent) +
  theme(legend.position = c(0.8, 0.8))

bec_zone_scatter <- vlce %>%
  separate(subzone, into = c("zone", "subzone")) %>%
  group_by(protected, zone) %>%
  summarize(count = sum(n)) %>%
  mutate(perc = count / sum(count)) %>%
  dplyr::select(!count) %>%
  pivot_wider(names_from = protected, values_from = perc) %>%
  ggplot(aes(x = protected, y = unprotected, colour = zone)) +
  geom_point() +
  scale_y_continuous(labels = scales::percent, limits = c(0, .25)) +
  scale_x_continuous(labels = scales::percent, limits = c(0, .25)) +
  labs(colour = NULL,
       x = "Protected",
       y = "Unprotected") +
  geom_abline(slope = 1, intercept = 0, lty = "dashed") +
  scale_colour_igv()

ggsave(here::here("outputs", "bec_zone_scatter.png"), 
       plot = bec_zone_scatter, device = "png")

# BEC subzone proportion of BC
bec_subzone_scatter <- vlce %>%
  group_by(protected, subzone) %>%
  summarize(count = sum(n)) %>%
  mutate(perc = count / sum(count)) %>%
  dplyr::select(!count) %>%
  pivot_wider(names_from = protected, values_from = perc) %>%
  separate(subzone, into = c("zone", "subzone")) %>%
  ggplot(aes(x = protected, y = unprotected, colour = zone)) +
  geom_point() +
  scale_y_continuous(labels = scales::percent) +
  scale_x_continuous(labels = scales::percent) +
  labs(colour = NULL,
       x = "Protected",
       y = "Unprotected") +
  geom_abline(slope = 1, intercept = 0, lty = "dashed") +
  scale_colour_igv()

ggsave(here::here("outputs", "bec_subzone_scatter.png"), 
       plot = bec_subzone_scatter, device = "png")

# Protected portions of subzones
per_prot_zone <- vlce %>% 
  group_by(subzone, protected) %>%
  summarize(count = sum(n)) %>%
  mutate(perc = count / sum(count)) %>%
  separate(subzone, into = c("zone", "subzone")) %>%
  filter(protected == "protected") %>%
  mutate(zone = fct_reorder(zone, perc)) 

n_zones <- per_prot_zone %>%
  count(zone)

bec_subzone_boxes <- per_prot_zone %>%
  left_join(n_zones) %>%
  mutate(label = paste0(zone, " (", n, ")"),
         label = fct_reorder(label, perc)) %>%
  ggplot() +
  geom_boxplot(aes(x = perc, y = label)) +
  geom_vline(aes(xintercept = 0.17, colour = "2020 Biodiversity Target (Global)"), lty = "dashed") +
  geom_vline(aes(xintercept = 0.10, colour = "2010 Biodiversity Target (Ecoregions)"), lty = "dashed") +
  scale_colour_aaas() +
  scale_x_continuous(labels = scales::percent) +
  labs(x = "Percent Protected",
       y = NULL,
       fill = NULL,
       colour = NULL) +
  theme(legend.position = c(0.75, 0.2))

ggsave(here::here("outputs", "bec_subzone_boxes.png"), 
       plot = bec_subzone_boxes, device = "png")

bec_prot_donut <- vlce %>%
  separate(subzone, into = c("zone", "subzone")) %>%
  group_by(zone, protected) %>%
  summarize(count = sum(n)) %>%
  mutate(perc = count / sum(count)) 

bec_perc_terr <- bec_prot_donut %>%
  summarize(count = sum(count)) %>%
  mutate(perc_terr = count / sum(count))

w <- sort(bec_perc_terr$perc_terr)
pos <- 0.5 * (cumsum(w) + cumsum(c(0, w[-length(w)])))

bec_conch_df <- bec_prot_donut %>%
  filter(protected == "protected") %>%
  left_join(keys$bec) %>%
  #left_join(bec_perc_terr, by = c("zone" = "zone")) %>%
  mutate(zone_nm = fct_reorder(zone_nm, perc),
         zone = fct_reorder(zone, perc, .fun = max)) 

write_csv(bec_conch_df, here::here("outputs", "bec_prop_protected.csv"))

bec_conch_df %>%
  ggplot(aes(x = fct_reorder(zone, perc), y = perc, fill = zone_nm)) +
  geom_bar(stat = "identity") +
  geom_hline(aes(yintercept = 0.17, colour = "2020 Biodiversity Target (Global)"), lty = "dotted", size = 1) +
  geom_hline(aes(yintercept = 0.10, colour = "2010 Biodiversity Target (Ecoregions)"), lty = "dotted", size = 1) +
  geom_hline(aes(yintercept = 0.154, colour = "Total BC Proportion Protected (15.4%)"), lty = "dotted") +
  geom_text(aes(x = 1, y = .12), label = "10%", colour = "black") +
  geom_text(aes(x = 1, y = .19), label = "17%") +
  scale_colour_aaas() +
  scale_fill_igv() +
  coord_polar() +
  theme_void() + 
  theme(axis.line = element_blank(),
        axis.title = element_blank(), 
        axis.ticks = element_blank(), 
        axis.text.y = element_blank(),
        #legend.position = "bottom",
        legend.box = "vertical") +
  labs(fill = NULL,
       colour = NULL)

ggsave(here::here("outputs", "bec_conch.png"), plot = bec_conch, device = "png")

vlce %>%
  separate(subzone, into = c("zone", "subzone")) %>%
  group_by(zone, protected) %>%
  summarize(count = sum(n)) %>%
  mutate(perc = count / sum(count),
         zone = fct_reorder(zone, perc)) %>%
  filter(protected == "protected") %>%
  ggplot() +
  geom_point(aes(x = perc, y = zone)) +
  geom_vline(xintercept = c(.10, .17), colour = "red") +
  scale_x_continuous(lim = c(0, .302), labels = scales::percent) +
  labs(x = "Percent Protected",
       y = NULL,
       fill = NULL)
```

VLCE Conch

```{r vlce-conch}
vlce_conch_df <- vlce %>%
  group_by(vlce, protected) %>%
  summarize(count = sum(n, na.rm = T)) %>%
  mutate(perc = count / sum(count)) %>%
  filter(protected == "protected") %>%
  left_join(keys$vlce, by = c("vlce" = "class_val")) %>%
  dplyr::select(name_clean, protected, perc, count) %>%
  ungroup()

vlce_conch <- vlce_conch_df %>%
  ggplot(aes(x = fct_reorder(as.factor(vlce), perc), y = perc, fill = fct_rev(fct_reorder(name_clean, vlce, .fun = max)))) +
  geom_bar(stat = "identity") +
  geom_hline(aes(yintercept = 0.17, colour = "2020 Biodiversity Target (Global)"), lty = "dotted", size = 1) +
  geom_hline(aes(yintercept = 0.10, colour = "2010 Biodiversity Target (Ecoregions)"), lty = "dotted", size = 1) +
  geom_hline(aes(yintercept = 0.154, colour = "Total BC Proportion Protected (15.4%)"), lty = "dotted") +
  geom_text(aes(x = 1, y = .12), label = "10%", colour = "black") +
  geom_text(aes(x = 1, y = .19), label = "17%") +
  scale_colour_aaas() +
  scale_fill_manual(values = rev(vlce_colours)) +
  coord_polar() +
  theme_void() + 
  theme(axis.line = element_blank(),
        axis.title = element_blank(), 
        axis.ticks = element_blank(), 
        axis.text.y = element_blank(),
        #legend.position = "bottom",
        legend.box = "vertical") +
  labs(fill = NULL,
       colour = NULL) +
  guides(fill = guide_legend(order = 2),
         colour = guide_legend(order = 1))
  
ggsave(here::here("outputs", "vlce_conch.png"), plot = vlce_conch, device = "png")
```



T-Test Plots

```{r t-tests}
t_tests_zonal <- t_tests %>%
  separate(subzone, into = c("zone", "subzone")) %>% 
  mutate(sig0.05 = ifelse(p.value < 0.05, T, F),
         sig0.01 = ifelse(p.value < 0.01, T, F)) %>%
  group_by(zone, variable) %>%
  summarize(sig0.05 = sum(sig0.05),
            sig0.01 = sum(sig0.01),
            total = n()) %>%
  mutate(per_sig0.05 = sig0.05 / total,
         per_sig0.01 = sig0.01 / total) %>%
  left_join(keys$continuous)

t_tests_scatter <- t_tests_zonal %>%
  filter(!variable %in% c("slope", "elev")) %>%
  mutate(axis_label = paste0(var_long, " (", unit, ")")) %>%
  ggplot(aes(x = per_sig0.01, y = axis_label)) +
  geom_point(aes(colour = zone), alpha = 0.5) +
  geom_text_repel(aes(label = zone), max.overlaps = 20) +
  labs(x = "Percent Significance",
       y = NULL) +
  scale_colour_igv() +
  labs(colour = NULL) +
  scale_x_continuous(labels = scales::percent)

ggsave(here::here("outputs", "t_tests_scatter.png"), plot = t_tests_scatter, device = "png")
  
```

Structure 3D Plot

```{r 3d-structure-subzone}
library(plot3D) # in use for 3d plot
library(plot3Drgl) # not in use
library(gridGraphics) # probably in use

bec_cols <- pal_igv("default")(16)
structure <- read_csv(here::here("data", "structure", "structure_means.csv"))

for_arrows_subzone <- structure %>%
  dplyr::select(!ends_with("total_biomass")) %>%
  dplyr::select(protected, subzone, starts_with("mean")) %>%
  pivot_wider(names_from = protected, values_from = starts_with("mean")) %>%
  separate(subzone, into = c("zone", "subzone")) %>%
  drop_na() #%>%
  #filter(zone != "SBPS") %>%
  
for_arrows_subzone <- for_arrows_subzone %>%
  mutate(id = group_indices(., zone))

# currently broken colouring of points
subzones_3d <- function() {
  arrows3D(for_arrows_subzone$mean_elev_cv_protected, 
           for_arrows_subzone$mean_loreys_height_protected, 
           for_arrows_subzone$mean_percentage_first_returns_above_2m_protected,
           for_arrows_subzone$mean_elev_cv_unprotected, 
           for_arrows_subzone$mean_loreys_height_unprotected, 
           for_arrows_subzone$mean_percentage_first_returns_above_2m_unprotected,
           col = bec_cols,
           lwd = 1, 
           #d = 3, 
           bty = "g",
           ticktype = "detailed",
           xlab = "\n Vertical Complexity",
           ylab = "\n Forest Height",
           zlab = "\n Canopy Cover",
           type = "cone")
  
  points3D(for_arrows_subzone$mean_elev_cv_protected, 
           for_arrows_subzone$mean_loreys_height_protected, 
           for_arrows_subzone$mean_percentage_first_returns_above_2m_protected,
           labels = for_arrows_subzone$zone,
           colvar = for_arrows_subzone$id,
           col = bec_cols, add = T,
           colkey = F,
           type = "p",
           pch = 19,
           clab = "BEC Zone"#,
           #colkey = list(at = c(1:max(for_arrows_subzone$id)), side = 4,
           #             addlines = T, labels = unique(for_arrows_subzone$zone))
           )
}


subzones_3d_scatter <- plot_grid(subzones_3d, bec_legend,
          scale = c(1.2, 1))

ggsave(here::here("outputs", "subzones_3d_scatter.png"),
       plot = subzones_3d_scatter, device = "png")

```

```{r 3d-structure-zone}

for_arrows_zone <- structure %>%
  separate(subzone, into = c("zone", "subzone")) %>%
  dplyr::select(!starts_with("sd")) %>%
  group_by(protected, zone) %>%
  summarize(mean_elev_cv = weighted.mean(mean_elev_cv, count),
            mean_percentage_first_returns_above_2m = weighted.mean(mean_percentage_first_returns_above_2m, count),
            mean_loreys_height = weighted.mean(mean_loreys_height, count),
            mean_total_biomass = weighted.mean(mean_total_biomass, count)) %>%
  pivot_wider(names_from = protected, values_from = starts_with("mean")) %>%
  #filter(zone != "SBPS") %>%
  mutate(id = row_number())

zones_3d <- function() {

  arrows3D(for_arrows_zone$mean_elev_cv_protected, 
           for_arrows_zone$mean_loreys_height_protected, 
           for_arrows_zone$mean_percentage_first_returns_above_2m_protected,
           for_arrows_zone$mean_elev_cv_unprotected, 
           for_arrows_zone$mean_loreys_height_unprotected, 
           for_arrows_zone$mean_percentage_first_returns_above_2m_unprotected,
           col = bec_cols,
           lwd = 1, 
           d = 3, 
           #bty = "g",
           ticktype = "detailed",
           xlab = "\n Vertical Complexity",
           ylab = "\n Forest Height",
           zlab = "\n Canopy Cover",
           type = "cone")
  
  points3D(for_arrows_zone$mean_elev_cv_protected, 
           for_arrows_zone$mean_loreys_height_protected, 
           for_arrows_zone$mean_percentage_first_returns_above_2m_protected,
           labels = for_arrows_zone$zone,
           colvar = for_arrows_zone$id,
           col = bec_cols, 
           add = T,
           colkey = F,
           type = "p",
           pch = 19,
           clab = "BEC Zone"
           #colkey = list(at = c(1:max(for_arrows_zone$id)), side = 4,
          #               addlines = T, labels = for_arrows_zone$zone)
           )
}

zones_3d_scatter <- plot_grid(zones_3d, bec_legend,
          scale = c(1.2, 1))

ggsave(here::here("outputs", "zones_3d_scatter.png"),
       plot = zones_3d_scatter, device = "png")

```

structure scatterplots

```{r structure-scatter}
structure_scatter <- structure %>% 
  dplyr::select(!c(starts_with("sd"), "count")) %>%
  pivot_longer(starts_with("mean"), 
               names_to = "variable", 
               values_to = "value") %>%
  pivot_wider(names_from = protected, values_from = value) %>%
  separate(subzone, into = c("zone", "subzone")) %>%
  mutate(variable = str_remove(variable, "mean_")) %>%
  left_join(keys$continuous) %>%
  ggplot(aes(x = protected, y = unprotected, colour = zone)) +
  geom_point(alpha = 0.75) +
  geom_abline(intercept = 0, slope = 1, lty = "dashed", alpha = 0.5) +
  facet_wrap(~var_long, scales = "free") +
  scale_colour_igv() +
  labs(colour = NULL,
       x = "Protected",
       y = "Unprotected")

ggsave(here::here("outputs", "structure_scatter.png"),
       plot = structure_scatter, device = "png")
```

Latitude Disturbance

```{r lat-dist}
bc_bounds <- read_sf(here::here("data", "shapefiles", "bc_boundary.shp"))
bc_bbox <- bc_bounds %>% st_bbox()

lat_min <- bc_bbox$ymin

lat_agg <- 1000

lat_df <- lat_dist %>% 
  mutate(latitude = latitude %/% lat_agg * lat_agg,
         Change_Attribution = ifelse(!(Change_Attribution %in% c(1, 2)), 
                                     NA, 
                                     Change_Attribution)) %>%
  group_by(protected, latitude, Change_Attribution) %>%
  summarize(count = sum(count)) %>%
  mutate(perc = count / sum(count),
         Change_Attribution = case_when(Change_Attribution == 1 ~ "Fire",
                                        Change_Attribution == 2 ~ "Harvest",
                                        TRUE ~ "None")) %>%
  mutate(latitude = (latitude * 30) + lat_min)

dist_colours <-  pal_igv("default")(3)[c(2, 3, 1)]

lat_plot <- lat_df %>%
  ggplot(aes(x = latitude, y = perc, fill = Change_Attribution)) +
  geom_area() +
  facet_wrap(~str_to_title(protected)) +
  scale_y_continuous(labels = scales::percent) +
  coord_flip(ylim = c(.75, 1)) +
  labs(x = "Latitude",
       y = "Percent Disturbed",
       fill = "Disturbance") +
  theme(legend.position = "bottom") +
  scale_fill_manual(values = dist_colours)

lat_plot

lat_prot <- lat_df %>%
  group_by(latitude, protected) %>%
  summarize(count = sum(count)) %>%
  mutate(perc = count / sum(count)) %>%
  filter(protected == "protected") %>%
  ggplot(aes(x = latitude, y = perc)) +
  #geom_smooth() +
  #geom_point() +
  geom_area() +
  scale_y_continuous(labels = scales::percent, limits = c(0, 1)) +
  labs(x = NULL,
       y = "Percent Protected",
       fill = NULL) +
  theme(axis.text.y = element_blank(),
        legend.position = c(0.7, 0.85)) +
  coord_flip()
  

latitude_disturbance_plot <- plot_grid(lat_plot, lat_prot,
          rel_widths = c(3, 1),
          align = 'h', axis = 'tb')

ggsave(here::here("outputs", "latitude_disturbance_plot.png"),
       plot = latitude_disturbance_plot, device = "png")
```



overall vlce for more t tests maybe?

```{r forest-wetland}
forest <- vlce %>%
  left_join(keys$vlce, by = c("vlce" = "class_val")) %>%
  group_by(protected, subzone, forest) %>%
  summarize(count = sum(n)) %>%
  mutate(perc = count / sum(count, na.rm = T)) %>%
  dplyr::select(!count) %>%
  filter(forest == "Forest") %>%
  pivot_wider(names_from = protected, values_from = perc) %>%
  drop_na() %>%
  separate(subzone, into = c("zone", "subzone")) %>%
  rename(class = forest)

wetland <- vlce %>%
  left_join(keys$vlce, by = c("vlce" = "class_val")) %>%
  group_by(protected, subzone, wetland) %>%
  summarize(count = sum(n)) %>%
  mutate(perc = count / sum(count)) %>%
  dplyr::select(!count) %>%
  filter(wetland == "Wetland") %>%
  pivot_wider(names_from = protected, values_from = perc) %>%
  drop_na() %>%
  separate(subzone, into = c("zone", "subzone")) %>%
  rename(class = wetland)

f_w <- bind_rows(forest, wetland)

f_w_scatter <- f_w %>%
  ggplot(aes(x = protected, y = unprotected, colour = zone)) +
  geom_point() +
  geom_abline(intercept = 0, slope = 1, lty = "dashed", alpha = 0.5) +
  scale_colour_igv() +
  scale_y_continuous(labels = scales::percent) +
  scale_x_continuous(labels = scales::percent) +
  #coord_cartesian(xlim = c(0, .15), ylim = c(0, .15)) +
  facet_wrap(~class) +
  labs(colour = NULL,
       x = "Protected",
       y = "Unprotected") +
  coord_equal()

ggsave(here::here("outputs", "forest_wetland_scatter.png"), plot = f_w_scatter,
       device = "png")

```


```{r map}
bec_sf <- read_sf(here::here("data", "shapefiles", "bec_zones.shp"))

bec_zones <- aggregate(x = bec_sf$are_sqm, by = list(bec_sf$zone),
                       FUN = sum, na.rm = TRUE,
                       do.union = T)

bec_zones = bec_sf %>% group_by(zone) %>%
  summarize(area = sum(are_sqm, na.rm = TRUE))

bc_bounds <- read_sf(here::here("data", "shapefiles", "bc_boundary.shp"))

bec_zones_terr <- bec_zones %>%
  st_intersection(bc_bounds)

parks <- read_sf(here::here("data", "shapefiles", "bc_ppa.shp"))

provinces <- getData(country = "Canada", level = 1)

prov_sf <- provinces %>%
  st_as_sf() %>%
  st_transform(3005)

bbox <- bc_bounds %>%
  st_bbox()

map <- ggplot() +
  geom_sf(data = bec_zones_terr, aes(fill = zone), colour = NA) +
  geom_sf(data = parks, aes(lty = "dotted"), fill = "Green", alpha = 0.75) +
  geom_sf(data = prov_sf) %>%
  scale_linetype_manual(labels = "Protected Areas", values = "solid") +
  scale_fill_igv() +
  labs(fill = NULL,
       linetype = NULL) +
  coord_sf()

ggsave(here::here("outputs", "bec_map.png"), plot = map, device = "png")
```

zoomed vignette section

```{r vignette}

name2 <- "CDF_mm"
name <- "ESSF_wvp"
subzone_csv <- read_csv(here::here("data", "all_vars", "sampled", paste0(name, "-2015.csv")))
subzone_csv <- bind_rows(read_csv(here::here("data", "all_vars", "sampled", paste0(name, "-2015.csv"))),
          read_csv(here::here("data", "all_vars", "sampled", paste0(name2, "-2015.csv"))))
subzone_formatted <- subzone_csv %>% 
  select(subzone, protected, elev_cv:total_biomass) %>%
  pivot_longer(elev_cv:total_biomass) %>%
  left_join(keys$continuous, by = c("name" = "variable")) %>%
  left_join(t_tests, by = c("subzone", "name" = "variable")) %>%
  mutate(title = ifelse(p.value < 0.01, paste(var_long, "*", ""), var_long))
subzone_formatted %>%
  ggplot(aes(x = protected, y = value, fill = str_to_title(protected))) +
  geom_boxplot(outlier.alpha = 0.5) +
  facet_grid(str_replace(subzone, "_", " ")~var_long, scales = "free") +
  labs(x = NULL,
       y = NULL,
       fill = NULL) +
  #theme_classic() +
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        legend.position = "bottom",
        panel.grid.major = element_blank())
subzone_formatted %>%
  ggplot(aes(x = value, y = protected, fill = protected)) +
  geom_density_ridges(alpha = 0.75, quantile_lines = TRUE) +
  facet_wrap(~title, scales = "free") +
  labs(x = NULL,
       y = NULL,
       fill = NULL,
       title = name)
subzone_formatted %>%
  ggplot(aes(x = value, y = str_to_title(protected), fill = stat(quantile)), alpha = 0.75) +
  stat_density_ridges(geom = "density_ridges_gradient", 
                      calc_ecdf = T, 
                      quantile_lines = TRUE) +
  facet_wrap(~title, scales = "free") +
  labs(x = NULL,
       y = NULL,
       fill = NULL) +
  scale_fill_scico_d(name = "Quartiles", alpha = 0.75)
```

```{r cdf}
vlce_colours <- keys$vlce %>% pull(ntems_colour)

cdf_sample <- read_csv(here::here("data", "all_vars", "sampled", "CDF_mm-2015.csv"))

cdf_all <- read_csv(here::here("data", "all_vars", "CDF_mm-2015.csv"))

cdf_vlce <- cdf_all %>%
  filter(vlce != 0) %>%
  group_by(protected, vlce) %>%
  summarize(count = n()) %>%
  ungroup() %>%
  complete(protected, vlce, fill = list(count = 0)) %>%
  left_join(keys$vlce, by = c("vlce" = "class_val")) %>% 
  group_by(protected) %>%
  mutate(perc = count / sum(count, na.rm = T),
         name_clean = fct_reorder(name_clean, vlce)) 

cdf_vlce %>%
  ggplot(aes(x = protected, y = perc, fill = fct_rev(name_clean))) +
  geom_bar(stat = "identity", position = "stack") +
  guides(fill = guide_legend(reverse = F)) +
  theme_void() +
  #theme(legend.position = "bottom") +
  coord_polar(theta = "y") +
  labs(fill = "Land Cover") +
  scale_fill_manual(values = rev(vlce_colours)) +
  guides(fill = guide_legend(title.position = "top",
                             title.hjust = 0.5))

cdf_vlce %>%
  dplyr::select(protected, name_clean, perc) %>%
  pivot_wider(names_from = protected, values_from = perc) %>%
  ggplot(aes(x = protected, y = unprotected, colour = name_clean)) +
  geom_point() +
  geom_abline(intercept = 0, slope = 1, alpha = 0.5, lty = "dotted") +
  scale_colour_manual(values = vlce_colours) +
  lims(x = c(0, 0.6),
       y = c(0, 0.6))

cdf_vlce %>%
  ggplot(aes(x = fct_reorder(as.factor(vlce), perc), y = perc, fill = fct_rev(fct_reorder(name_clean, vlce, .fun = max)))) +
  geom_bar(stat = "identity") +
  geom_hline(aes(yintercept = 0.17, colour = "2020 Biodiversity Target (Global)"), lty = "dotted", size = 1) +
  geom_hline(aes(yintercept = 0.10, colour = "2010 Biodiversity Target (Ecoregions)"), lty = "dotted", size = 1) +
  geom_hline(aes(yintercept = 0.154, colour = "Total BC Proportion Protected (15.4%)"), lty = "dotted") +
  geom_text(aes(x = 1, y = .12), label = "10%", colour = "black") +
  geom_text(aes(x = 1, y = .19), label = "17%") +
  scale_colour_aaas() +
  scale_fill_manual(values = rev(vlce_colours)) +
  coord_polar() +
  theme_void() + 
  theme(axis.line = element_blank(),
        axis.title = element_blank(), 
        axis.ticks = element_blank(), 
        axis.text.y = element_blank(),
        #legend.position = "bottom",
        legend.box = "vertical") +
  labs(fill = NULL,
       colour = NULL) +
  guides(fill = guide_legend(order = 2),
         colour = guide_legend(order = 1))

cdf_dist <- egg()

dist_colours <-  pal_igv("default")(3)[c(2, 3, 1)]

cdf_conch <- cdf_all %>%
  group_by(protected, Change_Attribution) %>%
  summarize(count = n()) %>%
  ungroup() %>%
  complete(protected, Change_Attribution, fill = list(count = 0)) %>%
  group_by(protected) %>%
  mutate(Change_Attribution = ifelse(!(Change_Attribution %in% c(1, 2)), 
                                     NA, 
                                     Change_Attribution)) %>%
  group_by(protected, Change_Attribution) %>%
  summarize(count = sum(count)) %>%
  mutate(perc = count / sum(count),
         Change_Attribution = case_when(Change_Attribution == 1 ~ "Fire",
                                        Change_Attribution == 2 ~ "Harvest",
                                        TRUE ~ "None")) %>%
  ggplot(aes(x = protected, y = perc, fill = Change_Attribution)) +
  geom_bar(stat = "identity", position = "stack") +
  guides(fill = guide_legend(reverse = F)) +
  theme_void() +
  #theme(legend.position = "bottom") +
  coord_polar(theta = "y") +
  labs(fill = "Land Cover") +
  guides(fill = guide_legend(title.position = "top",
                             title.hjust = 0.5)) +
  scale_fill_manual(values = dist_colours)

ggsave(here::here("outputs", "cdf_conch.png"), plot = cdf_conch, device = "png")

```

